name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        
    - name: Download dependencies
      run: go mod download
      
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        BINARY_NAME="terraform-provider-kind"
        if [ "$GOOS" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        go build -o ${BINARY_NAME} \
          -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" \
          .
          
        # Create archive
        ARCHIVE_NAME="terraform-provider-kind_${GITHUB_REF#refs/tags/}_${GOOS}_${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          zip "${ARCHIVE_NAME}.zip" ${BINARY_NAME}
        else
          tar -czf "${ARCHIVE_NAME}.tar.gz" ${BINARY_NAME}
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-provider-kind-${{ matrix.goos }}-${{ matrix.goarch }}
        path: terraform-provider-kind*
        
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: '**/terraform-provider-kind*'
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}